services:
  app:
    image: springboot-devops-demo:latest
    build: .
    container_name: springboot-devops-demo
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: "prod"
      JAVA_OPTS: "-XX:MaxRAMPercentage=75"
    restart: unless-stopped
